### ISSUE TITLE
Cutoff + floating over apps + autohide not working properly + settings not saved + darkmode

### ISSUE THREAD

**Issue by regularvykings** [Droptop-Four/Basic-Version#8]
Whenever I try to use any of the system task, but that I mean change language or connect to wifi, doesn't matter whether I use the top bar or the windows taskbar, they get cutoff at the top.

_Screenshot:_
![2021-11-23](https://user-images.githubusercontent.com/64218662/142969802-9d6fbbf9-916d-433f-ad69-b3f9fae821ec.png)

Occasionally the bar would float over apps and cover some functions, but this can be changed with changing the zoom. Still annoying though.

Whenever I select always hide droptop and bring my mouse over to the top, the bar doesn't show itself, desktop or apps.

I recently updated to the newer version and none of the settings I had were saved.

Windows dark and light doesn't matter, the bar is alayways light mode. Maybe it could be fixed?

**Comment by 66Bunz** [comment]
> Whenever I try to use any of the system task, but that I mean change language or connect to wifi, doesn't matter whether I use the top bar or the windows taskbar, they get cutoff at the top.

This is a known issue and more of a bug with Windows 11 than with Droptop.
We recommend to take the screenshot and send them to Microsoft through their feedback hub (`WinKey + F`).

> _Screenshot:_ ![2021-11-23](https://user-images.githubusercontent.com/64218662/142969802-9d6fbbf9-916d-433f-ad69-b3f9fae821ec.png)
> 
> Occasionally the bar would float over apps and cover some functions, but this can be changed with changing the zoom. Still annoying though.

What zoom are you changing?

> Whenever I select always hide droptop and bring my mouse over to the top, the bar doesn't show itself, desktop or apps.

Recently some people started to have the same problem, come to the [Droptop Four discord server](https://discord.gg/aGQ6uE4Fgp) to discuss this more.

> I recently updated to the newer version and none of the settings I had were saved.

This happened because this version is the previous to a majour release that changed a lot of things about how droptop worls. Unfortunately this happens

> Windows dark and light doesn't matter, the bar is alayways light mode. Maybe it could be fixed?

Droptop by default takes the colors of the desktop wallpaper, but you can change every one of them from the droptop settings!

**Comment by 66Bunz** [comment]
Closed for inactivity
